### ISSUE TITLE
Integrate into IoTGoat project? 

### ISSUE THREAD

**Issue by scriptingxss** [lefanous/iotgoat#1]
Hello, 

Thank you for creating this IoTGoat container project. Curious if you would be willing in integrate this into the OWASP project? If so, feel free to send over a PR when you can. We have an open issue that pointed me to your project [here](https://github.com/OWASP/IoTGoat/issues/4#issuecomment-2371553567) that would be awesome to close out with your contribution! :D  

Cheers, 
Aaron

**Comment by lefanous** [comment]
Sure! Will create a PR asap. Thank you for reaching out!

Best Regards,
Abdallah

**Comment by lefanous** [comment]
I've now created a PR: https://github.com/OWASP/IoTGoat/pull/11
